"""
Marketing Intelligence Agent
============================
The strategic brain of the content system. Generates content strategies, 
ideas, and schedules based on client niche, audience, and trends.

RESPONSIBILITIES:
- Analyze client niche, audience, and goals
- Generate weekly/monthly content strategies
- Create content ideas with hooks, angles, and formats
- Recommend platforms and optimal posting times
- Feed ideas to Content Creation Agent, Video Creator, and Image Generator

INTEGRATION:
- Uses RAG for client context (business info, past content, audience insights)
- Outputs structured ContentIdea objects consumed by other agents
- Works with prompt_templates.py to ensure generated ideas map to valid templates
"""

import asyncio
import json
import os
import re
from dataclasses import dataclass, asdict
from typing import List, Optional, Dict, Any
from datetime import datetime, timedelta
from enum import Enum
from anthropic import Anthropic
from dotenv import load_dotenv

# Marketing Intelligence API clients
from newsapi import NewsApiClient
from tavily import TavilyClient
import requests

# Import RAG system for client context
import sys
sys.path.append(os.path.dirname(os.path.dirname(__file__)))
from agents.rag_system import RAGSystem
from agents.knowledge_base import KnowledgeBase
from agents.strategy_templates import get_templates
from agents.client_profile_manager import ClientProfileManager, ClientProfile
from prompt_templates import PROMPT_TEMPLATES, get_prompt_template

load_dotenv()


def _repair_truncated_json(raw: str) -> str:
    """Best-effort repair of JSON that was truncated mid-string by max_tokens.

    Handles common cases:
    - Unterminated string: close the open quote
    - Unbalanced brackets/braces: close them
    - Trailing commas before closers
    """
    # Remove trailing commas before } or ]
    raw = re.sub(r',\s*$', '', raw.rstrip())

    # Count open/close braces and brackets
    in_str = False
    esc = False
    opens = []
    for ch in raw:
        if esc:
            esc = False
            continue
        if ch == '\\':
            esc = True
            continue
        if ch == '"':
            in_str = not in_str
            continue
        if in_str:
            continue
        if ch in ('{', '['):
            opens.append(ch)
        elif ch == '}' and opens and opens[-1] == '{':
            opens.pop()
        elif ch == ']' and opens and opens[-1] == '[':
            opens.pop()

    # If we're inside a string, close it
    if in_str:
        raw += '"'

    # Close any remaining open braces/brackets
    for opener in reversed(opens):
        raw += ']' if opener == '[' else '}'

    # Final trailing comma cleanup
    raw = re.sub(r',\s*([}\]])', r'\1', raw)
    return raw


class ContentFormat(Enum):
    """Supported content formats mapped to prompt_templates.py"""
    POST = "post"           # Standard text posts
    REEL = "reel"           # Short video content
    STORY = "story"         # Ephemeral content
    CAROUSEL = "carousel"   # Multi-image posts
    VIDEO = "video"         # Long-form video
    ARTICLE = "article"     # Long-form text (LinkedIn, Blog)
    THREAD = "thread"       # Twitter threads
    AD = "ad"               # Paid advertising content


class ContentGoal(Enum):
    """Content goals mapped to prompt_templates.py"""
    ENGAGEMENT = "views_engagement"
    FOLLOWER_GROWTH = "follower_growth"
    CONVERSIONS = "conversions_sales"


class Priority(Enum):
    """Content priority levels"""
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


@dataclass
class ContentIdea:
    """
    A single content idea generated by the Marketing Intelligence Agent.
    This is the primary output consumed by other agents.
    """
    idea_id: str
    topic: str
    angle: str                          # The unique perspective/hook
    format: str                         # ContentFormat value
    goal: str                           # ContentGoal value
    recommended_platforms: List[str]    # e.g., ["instagram", "tiktok"]
    hooks: List[str]                    # Opening lines/hooks to use
    keywords: List[str]                 # SEO/hashtag keywords
    priority: str                       # Priority value
    reasoning: str                      # Why this idea was generated
    estimated_engagement: str           # low/medium/high
    best_posting_time: Optional[str] = None
    media_type: str = "image"           # image, video, carousel, none
    call_to_action: Optional[str] = None
    created_at: str = None
    
    def __post_init__(self):
        if self.created_at is None:
            self.created_at = datetime.now().isoformat()
    
    def to_dict(self) -> Dict:
        return asdict(self)
    
    def to_content_request(self) -> Dict:
        """Convert to format expected by ContentCreationAgent"""
        return {
            "platform": self.recommended_platforms[0] if self.recommended_platforms else "instagram",
            "content_type": self.format,
            "topic": f"{self.topic}: {self.angle}",
            "goal": self.goal,
            "hooks": self.hooks,
            "keywords": self.keywords
        }


@dataclass
class ContentStrategy:
    """
    Weekly/monthly content strategy output.
    Contains multiple ContentIdeas organized by day/time.
    """
    strategy_id: str
    client_id: str
    period: str                         # "weekly" or "monthly"
    start_date: str
    end_date: str
    ideas: List[ContentIdea]
    content_mix: Dict[str, int]         # e.g., {"video": 40, "image": 40, "article": 20}
    posting_frequency: int              # Posts per week
    themes: List[str]                   # Overall themes for the period
    notes: str                          # Strategic notes
    created_at: str = None
    
    def __post_init__(self):
        if self.created_at is None:
            self.created_at = datetime.now().isoformat()
    
    def to_dict(self) -> Dict:
        result = asdict(self)
        result["ideas"] = [idea.to_dict() for idea in self.ideas]
        return result


class MarketingIntelligenceAgent:
    """
    The strategic brain that generates content ideas and strategies.
    
    Usage:
        agent = MarketingIntelligenceAgent(client_id="demo_client")
        
        # Generate single batch of ideas
        ideas = await agent.generate_content_ideas(
            niche="AI automation for small businesses",
            num_ideas=5
        )
        
        # Generate full weekly strategy
        strategy = await agent.generate_weekly_strategy(
            niche="AI automation for small businesses"
        )
    """
    
    # Supported platforms mapped to prompt_templates.py
    SUPPORTED_PLATFORMS = list(PROMPT_TEMPLATES.keys())
    
    # Platform-specific format mappings
    PLATFORM_FORMATS = {
        "instagram": ["post", "reel", "story", "carousel"],
        "facebook": ["post", "reel", "story", "ad"],
        "tiktok": ["video", "story"],
        "twitter": ["post", "thread"],
        "linkedin": ["post", "article", "carousel"],
        "youtube": ["video", "short"],
        "pinterest": ["pin", "idea_pin"],
        "blog": ["article", "listicle"],
    }
    
    # Optimal posting times by platform (EST)
    OPTIMAL_TIMES = {
        "instagram": ["9:00 AM", "12:00 PM", "7:00 PM"],
        "facebook": ["9:00 AM", "1:00 PM", "4:00 PM"],
        "tiktok": ["7:00 AM", "12:00 PM", "7:00 PM"],
        "twitter": ["8:00 AM", "12:00 PM", "5:00 PM"],
        "linkedin": ["7:00 AM", "12:00 PM", "5:00 PM"],
        "youtube": ["2:00 PM", "4:00 PM"],
        "pinterest": ["8:00 PM", "11:00 PM"],
    }
    
    def __init__(self, client_id: str):
        self.client_id = client_id
        self.claude_client = Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))
        from utils.ai_config import CLAUDE_SONNET
        self.model = CLAUDE_SONNET
        self.rag = RAGSystem()
        self._idea_counter = 0
        
        # Load client profile (niche, platforms, content pillars)
        self.profile_manager = ClientProfileManager()
        self.client_profile: Optional[ClientProfile] = self.profile_manager.get_client_profile(client_id)
        
        # Initialize persistent knowledge base for deep research
        self.knowledge_base = KnowledgeBase()
        
        # Initialize strategy templates for proven frameworks
        self.strategy_templates = get_templates()
        print(f"   ✅ Loaded {len(self.strategy_templates.templates)} strategy frameworks")
        
        # Initialize intelligence API clients
        self.newsapi_key = os.getenv("NEWSAPI_KEY")
        self.newsapi = NewsApiClient(api_key=self.newsapi_key) if self.newsapi_key else None
        
        # Ensure dotenv is loaded (Railway sets env vars directly, local uses .env)
        try:
            from dotenv import load_dotenv
            load_dotenv()
        except ImportError:
            pass

        # YouTube data is accessed via Late API (posting), not YouTube Data API
        self.youtube = None

        self.tavily_key = os.getenv("TAVILY_API_KEY")
        self.tavily = TavilyClient(api_key=self.tavily_key) if self.tavily_key else None
        
        self.meta_access_token = os.getenv("INSTAGRAM_ACCESS_TOKEN")
    
    def _generate_idea_id(self) -> str:
        """Generate unique idea ID"""
        self._idea_counter += 1
        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
        return f"idea_{self.client_id}_{timestamp}_{self._idea_counter}"
    
    def _generate_strategy_id(self) -> str:
        """Generate unique strategy ID"""
        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
        return f"strategy_{self.client_id}_{timestamp}"
    
    def _load_performance_data(self) -> str:
        """
        Load the most recent analytics report for this client from disk and
        return a formatted string describing last week's top-performing
        content so it can be injected into the Claude content-ideas prompt.
        Returns empty string when no report is available.
        """
        try:
            import glob as _glob
            report_dir = os.path.join("storage", "analytics", self.client_id)
            if not os.path.isdir(report_dir):
                return ""
            report_files = sorted(
                _glob.glob(os.path.join(report_dir, "report_*.json")),
                reverse=True,
            )
            if not report_files:
                return ""
            with open(report_files[0]) as _f:
                report = json.load(_f)

            lines = []
            best = report.get("best_platform", "")
            if best:
                lines.append(f"Best performing platform last week: {best}")

            for p in report.get("platforms", []):
                name = p.get("platform", "")
                er   = p.get("engagement_rate", 0)
                al   = p.get("avg_likes", 0)
                ac   = p.get("avg_comments", 0)
                top  = p.get("top_post_id", "")
                entry = (f"  {name}: engagement_rate={er:.2f}%, "
                         f"avg_likes={al:.0f}, avg_comments={ac:.0f}")
                if top:
                    entry += f" (top post id: {top})"
                lines.append(entry)

            for rec in report.get("recommendations", [])[:3]:
                lines.append(f"Performance insight: {rec}")

            return "\n".join(lines) if lines else ""
        except Exception:
            return ""

    def _get_client_context(self, niche: str, additional_context: str = "") -> str:
        """Retrieve client context from RAG — always tries the knowledge base first."""
        # Build a prioritised list of queries: business name beats niche alone
        biz_name = ""
        if self.client_profile:
            biz_name = getattr(self.client_profile, "business_name", "") or ""
        queries = [q for q in [biz_name, niche, f"{niche} content strategy", "content strategy"] if q]
        # Deduplicate while preserving order
        seen: set = set()
        unique_queries = [q for q in queries if not (q in seen or seen.add(q))]

        print(f"🔍 RAG lookup for [{self.client_id}] — {len(unique_queries)} queries: {unique_queries}")

        for i, query in enumerate(unique_queries, 1):
            try:
                results = self.rag.search(query, self.client_id, limit=5, score_threshold=0.2)
                print(f"   Query {i}/{len(unique_queries)}: '{query}' → {len(results)} results (threshold=0.2)")
                if results:
                    context = "\n".join([f"- {r['text'][:300]}" for r in results])
                    print(f"✅ RAG context loaded for [{self.client_id}] via query='{query}' ({len(results)} chunks)")
                    return f"Client Knowledge:\n{context}\n\n{additional_context}"
            except Exception as e:
                print(f"⚠️ RAG search failed (query='{query}'): {e}")

        # Absolute last-resort: score_threshold=0.0 returns best matches regardless of score
        fallback_query = biz_name or niche
        try:
            results = self.rag.search(fallback_query, self.client_id, limit=3, score_threshold=0.0)
            print(f"   Absolute fallback query '{fallback_query}' (threshold=0.0) → {len(results)} results")
            if results:
                context = "\n".join([f"- {r['text'][:300]}" for r in results])
                print(f"✅ RAG context loaded for [{self.client_id}] via absolute fallback ({len(results)} chunks)")
                return f"Client Knowledge:\n{context}\n\n{additional_context}"
        except Exception as e:
            print(f"⚠️ RAG absolute fallback failed: {e}")

        print(f"❌ No RAG results for [{self.client_id}] across all thresholds — check if knowledge docs are indexed")

        # Build a structured profile fallback from the client profile fields
        # so Claude always has rich business context even without RAG docs.
        profile_context = self._build_profile_context(niche)
        parts = [p for p in [profile_context, additional_context] if p]
        return "\n\n".join(parts) if parts else f"Business Niche: {niche}"
    
    def _build_profile_context(self, niche: str) -> str:
        """Assemble a structured context block from the client profile fields.

        Called when RAG returns no results so Claude still understands the
        business beyond a bare niche label.  Every field is pulled
        dynamically from the profile — nothing is hardcoded per niche.
        """
        if not self.client_profile:
            return f"Business Niche: {niche}"

        lines = []
        biz_name = getattr(self.client_profile, "business_name", None) or getattr(self.client_profile, "client_name", None)
        if biz_name:
            lines.append(f"Business Name: {biz_name}")
        lines.append(f"Niche / Industry: {niche}")
        biz_desc = getattr(self.client_profile, "business_description", None)
        if biz_desc:
            lines.append(f"About the Business:\n{biz_desc}")
        tone = getattr(self.client_profile, "tone", None)
        if tone:
            lines.append(f"Brand Voice / Tone: {tone}")
        kw = getattr(self.client_profile, "keywords", None)
        if kw and isinstance(kw, list) and kw:
            lines.append(f"Key Topics & Keywords: {', '.join(kw)}")
        pillars = getattr(self.client_profile, "content_pillars", None)
        if pillars and isinstance(pillars, list) and pillars:
            lines.append(f"Content Pillars: {', '.join(pillars)}")
        platforms = getattr(self.client_profile, "platforms", None)
        if platforms and isinstance(platforms, list) and platforms:
            lines.append(f"Active Platforms: {', '.join(platforms)}")

        if not lines:
            return f"Business Niche: {niche}"
        return "**CLIENT BUSINESS PROFILE:**\n" + "\n".join(lines)

    def _get_deep_research_context(self, platforms: List[str], themes: List[str] = None) -> str:
        """
        Retrieve deep research insights from the KnowledgeBase.
        
        Searches for platform-specific algorithm knowledge, viral patterns,
        and strategy frameworks to inform content idea generation.
        """
        research_context = ""
        search_queries = []
        
        # Platform-specific algorithm research
        platform_queries = {
            "instagram": "Instagram algorithm 2025 engagement reach Reels",
            "tiktok": "TikTok viral video patterns FYP algorithm hooks",
            "linkedin": "LinkedIn B2B content strategy algorithm posts",
            "facebook": "Facebook algorithm 2025 organic reach engagement",
            "youtube": "YouTube algorithm trending video optimization",
            "twitter": "Twitter algorithm engagement viral tweets"
        }
        
        # Add platform queries
        for platform in platforms:
            if platform.lower() in platform_queries:
                search_queries.append(platform_queries[platform.lower()])
        
        # Add general strategy queries
        search_queries.extend([
            "viral content patterns hooks storytelling",
            "content pillar strategy mix educational entertaining",
            "hashtag strategy optimal best practices",
            "posting times optimal engagement"
        ])
        
        # Add theme-specific queries
        if themes:
            for theme in themes[:3]:  # Limit to avoid token overflow
                search_queries.append(f"{theme} content strategy tactics")
        
        print(f"\n📚 Searching deep research knowledge base...")
        
        all_insights = []
        seen_texts = set()  # Deduplicate
        
        for query in search_queries[:6]:  # Limit queries to control API costs
            try:
                results = self.knowledge_base.search(
                    query=query,
                    tags=["deep_research"],
                    limit=2
                )
                
                for r in results:
                    # Deduplicate by first 100 chars
                    text_key = r["text"][:100]
                    if text_key not in seen_texts and r["score"] > 0.75:
                        seen_texts.add(text_key)
                        all_insights.append({
                            "text": r["text"][:500],  # Truncate for prompt
                            "score": r["score"],
                            "tags": r["tags"]
                        })
            except Exception as e:
                print(f"   ⚠️ Search error for '{query[:30]}': {e}")
        
        # Sort by relevance and take top insights
        all_insights.sort(key=lambda x: x["score"], reverse=True)
        top_insights = all_insights[:5]
        
        if top_insights:
            print(f"   ✅ Found {len(top_insights)} relevant research insights")
            research_context = "\n**DEEP RESEARCH INSIGHTS (Algorithm & Strategy Knowledge):**\n"
            for i, insight in enumerate(top_insights, 1):
                # Clean up the text
                text = insight["text"].replace("\n", " ").strip()
                research_context += f"\n{i}. {text}\n"
        else:
            print(f"   ℹ️ No deep research found (run: python agents/knowledge_base.py ingest ...)")
        
        return research_context
    
    def _get_strategy_framework(self, template_type: str, niche: str) -> str:
        """
        Get proven strategy framework for client niche.
        
        Args:
            template_type: Type of strategy (content_pillars, hooks, hashtag, algorithm_optimization, posts)
            niche: Client niche (coaching, ecommerce, saas, b2b, health, wellness)
        
        Returns:
            Formatted strategy framework for Claude prompt
        """
        # Map niche keywords to strategy dict names.
        # Intentionally broad keyword coverage so most niches land on a
        # relevant framework without hardcoding every possible niche.
        niche_mapping = {
            # Coaching / consulting / services
            'coaching': 'COACHING_CONTENT_PILLARS_STRATEGY',
            'coach': 'COACHING_CONTENT_PILLARS_STRATEGY',
            'consultant': 'COACHING_CONTENT_PILLARS_STRATEGY',
            'consulting': 'COACHING_CONTENT_PILLARS_STRATEGY',
            'mentor': 'COACHING_CONTENT_PILLARS_STRATEGY',
            'speaker': 'COACHING_CONTENT_PILLARS_STRATEGY',
            'trainer': 'COACHING_CONTENT_PILLARS_STRATEGY',
            'advisor': 'COACHING_CONTENT_PILLARS_STRATEGY',
            # E-commerce / retail
            'ecommerce': 'ECOMMERCE_CONTENT_PILLARS_STRATEGY',
            'e-commerce': 'ECOMMERCE_CONTENT_PILLARS_STRATEGY',
            'store': 'ECOMMERCE_CONTENT_PILLARS_STRATEGY',
            'retail': 'ECOMMERCE_CONTENT_PILLARS_STRATEGY',
            'shop': 'ECOMMERCE_CONTENT_PILLARS_STRATEGY',
            'fashion': 'ECOMMERCE_CONTENT_PILLARS_STRATEGY',
            'boutique': 'ECOMMERCE_CONTENT_PILLARS_STRATEGY',
            'jewelry': 'ECOMMERCE_CONTENT_PILLARS_STRATEGY',
            # SaaS / B2B / tech / professional services
            'saas': 'SAAS_B2B_CONTENT_PILLARS_STRATEGY',
            'b2b': 'SAAS_B2B_CONTENT_PILLARS_STRATEGY',
            'software': 'SAAS_B2B_CONTENT_PILLARS_STRATEGY',
            'tech': 'SAAS_B2B_CONTENT_PILLARS_STRATEGY',
            'agency': 'SAAS_B2B_CONTENT_PILLARS_STRATEGY',
            'ai': 'SAAS_B2B_CONTENT_PILLARS_STRATEGY',
            'automation': 'SAAS_B2B_CONTENT_PILLARS_STRATEGY',
            'implementation': 'SAAS_B2B_CONTENT_PILLARS_STRATEGY',
            'digital': 'SAAS_B2B_CONTENT_PILLARS_STRATEGY',
            'marketing': 'SAAS_B2B_CONTENT_PILLARS_STRATEGY',
            'developer': 'SAAS_B2B_CONTENT_PILLARS_STRATEGY',
            'startup': 'SAAS_B2B_CONTENT_PILLARS_STRATEGY',
            'fintech': 'SAAS_B2B_CONTENT_PILLARS_STRATEGY',
            'data': 'SAAS_B2B_CONTENT_PILLARS_STRATEGY',
            'cyber': 'SAAS_B2B_CONTENT_PILLARS_STRATEGY',
            'cloud': 'SAAS_B2B_CONTENT_PILLARS_STRATEGY',
            'it service': 'SAAS_B2B_CONTENT_PILLARS_STRATEGY',
            'managed service': 'SAAS_B2B_CONTENT_PILLARS_STRATEGY',
            'legal': 'SAAS_B2B_CONTENT_PILLARS_STRATEGY',
            'accounting': 'SAAS_B2B_CONTENT_PILLARS_STRATEGY',
            'finance': 'SAAS_B2B_CONTENT_PILLARS_STRATEGY',
            'insurance': 'SAAS_B2B_CONTENT_PILLARS_STRATEGY',
            # Health / wellness / medical
            'health': 'HEALTH_WELLNESS_CONTENT_PILLARS_STRATEGY',
            'wellness': 'HEALTH_WELLNESS_CONTENT_PILLARS_STRATEGY',
            'fitness': 'HEALTH_WELLNESS_CONTENT_PILLARS_STRATEGY',
            'nutrition': 'HEALTH_WELLNESS_CONTENT_PILLARS_STRATEGY',
            'dental': 'HEALTH_WELLNESS_CONTENT_PILLARS_STRATEGY',
            'medical': 'HEALTH_WELLNESS_CONTENT_PILLARS_STRATEGY',
            'therapy': 'HEALTH_WELLNESS_CONTENT_PILLARS_STRATEGY',
            'chiropractic': 'HEALTH_WELLNESS_CONTENT_PILLARS_STRATEGY',
            'skincare': 'HEALTH_WELLNESS_CONTENT_PILLARS_STRATEGY',
            'beauty': 'HEALTH_WELLNESS_CONTENT_PILLARS_STRATEGY',
            'salon': 'HEALTH_WELLNESS_CONTENT_PILLARS_STRATEGY',
            'spa': 'HEALTH_WELLNESS_CONTENT_PILLARS_STRATEGY',
            'yoga': 'HEALTH_WELLNESS_CONTENT_PILLARS_STRATEGY',
        }
        
        # Detect niche from keywords
        niche_lower = niche.lower()
        dict_name = 'MULTI_PLATFORM_CONTENT_PILLARS_UNIVERSAL_STRATEGY'  # Default
        
        for keyword, strategy_name in niche_mapping.items():
            if keyword in niche_lower:
                dict_name = strategy_name
                break
        
        # Get the strategy template
        template_key = f'multi-platform_{template_type}_strategy'
        strategy = self.strategy_templates.get_strategy_dict(template_key, dict_name)
        
        if not strategy:
            return ""
        
        # Format for Claude prompt
        framework = f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📋 PROVEN STRATEGY FRAMEWORK: {strategy.get('framework_name', 'Unknown')}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**STRUCTURE GUIDELINES:**
{chr(10).join('• ' + item for item in strategy.get('structure', []))}

**BEST PRACTICES (Apply these in your ideas):**
{chr(10).join('• ' + item for item in strategy.get('best_practices', []))}

**KEY METRICS TO OPTIMIZE FOR:**
{chr(10).join('• ' + metric for metric in strategy.get('metrics', [])[:5])}
"""
        return framework
    
    def _get_available_templates(self) -> str:
        """Get list of available platform/format/goal combinations from prompt_templates.py"""
        available = []
        for platform, templates in PROMPT_TEMPLATES.items():
            if isinstance(templates, dict):
                for template_key in templates.keys():
                    available.append(f"{platform}: {template_key}")
        return "\n".join(available[:50])  # Limit to avoid token overflow
    
    # =============================================================================
    # INTELLIGENCE GATHERING METHODS
    # =============================================================================
    
    async def get_news_intelligence(self, niche: str, max_results: int = 5) -> List[Dict]:
        """
        Get trending news in client's niche using NewsAPI.
        
        Args:
            niche: Client's business niche/industry
            max_results: Maximum number of news articles to return
        
        Returns:
            List of news articles with title, description, source, URL
        """
        if not self.newsapi:
            print("⚠️ NewsAPI not configured. Set NEWSAPI_KEY in .env")
            return []
        
        try:
            print(f"📰 Fetching news intelligence for: {niche}")
            
            # Get recent news in the niche
            response = self.newsapi.get_everything(
                q=niche,
                language="en",
                sort_by="popularity",
                page_size=max_results
            )
            
            articles = []
            for article in response.get("articles", [])[:max_results]:
                articles.append({
                    "title": article.get("title", ""),
                    "description": article.get("description", ""),
                    "source": article.get("source", {}).get("name", "Unknown"),
                    "url": article.get("url", ""),
                    "published": article.get("publishedAt", "")
                })
            
            print(f"✅ Found {len(articles)} relevant news articles")
            return articles
            
        except Exception as e:
            print(f"❌ NewsAPI error: {e}")
            return []
    
    async def get_youtube_trends(self, keywords: List[str], max_results: int = 10) -> List[Dict]:
        """
        YouTube trending data is managed via Late API (posting/scheduling).
        YouTube Data API is not used — returns empty list.
        """
        return []
    
    async def get_competitive_intel(self, niche: str, query: str, max_results: int = 5) -> List[Dict]:
        """
        Get competitive intelligence using Tavily search.
        
        Args:
            niche: Client's business niche
            query: Specific search query (e.g., "top performing posts in [niche]")
            max_results: Maximum results to return
        
        Returns:
            List of search results with title, content, URL
        """
        if not self.tavily:
            print("⚠️ Tavily API not configured. Set TAVILY_API_KEY in .env")
            return []
        
        try:
            print(f"🔍 Tavily competitive research: {query}")
            
            # Perform search using Tavily
            response = self.tavily.search(
                query=f"{query} {niche}",
                max_results=max_results,
                search_depth="advanced"
            )
            
            results = []
            for result in response.get("results", [])[:max_results]:
                results.append({
                    "title": result.get("title", ""),
                    "content": result.get("content", "")[:300],
                    "url": result.get("url", ""),
                    "score": result.get("score", 0)
                })
            
            print(f"✅ Found {len(results)} competitive insights")
            return results
            
        except Exception as e:
            print(f"❌ Tavily API error: {e}")
            return []
    
    async def get_meta_insights(self, page_id: str) -> Dict:
        """
        Get client's Facebook/Instagram performance insights using Meta Graph API.
        
        Args:
            page_id: Facebook Page ID
        
        Returns:
            Dictionary with best posts, optimal times, audience data
        """
        if not self.meta_access_token:
            print("⚠️ Meta API not configured. Set INSTAGRAM_ACCESS_TOKEN in .env")
            return {}
        
        try:
            print(f"📊 Fetching Meta insights for page: {page_id}")
            
            # Get page posts with insights
            url = f"https://graph.facebook.com/v21.0/{page_id}/posts"
            params = {
                "access_token": self.meta_access_token,
                "fields": "id,message,created_time,insights.metric(post_impressions,post_engaged_users)",
                "limit": 25
            }
            
            response = requests.get(url, params=params)
            data = response.json()
            
            if "error" in data:
                print(f"❌ Meta API error: {data['error'].get('message')}")
                return {}
            
            posts = data.get("data", [])
            
            # Analyze top posts
            top_posts = []
            for post in posts[:10]:
                insights = post.get("insights", {}).get("data", [])
                engagement = 0
                impressions = 0
                
                for metric in insights:
                    if metric.get("name") == "post_engaged_users":
                        engagement = metric.get("values", [{}])[0].get("value", 0)
                    elif metric.get("name") == "post_impressions":
                        impressions = metric.get("values", [{}])[0].get("value", 0)
                
                top_posts.append({
                    "message": post.get("message", "")[:200],
                    "engagement": engagement,
                    "impressions": impressions,
                    "created_time": post.get("created_time", "")
                })
            
            # Sort by engagement
            top_posts.sort(key=lambda x: x["engagement"], reverse=True)
            
            print(f"✅ Analyzed {len(top_posts)} posts from Meta")
            return {
                "top_posts": top_posts[:5],
                "total_posts_analyzed": len(posts)
            }
            
        except Exception as e:
            print(f"❌ Meta API error: {e}")
            return {}
    
    async def gather_all_intelligence(self, niche: str, keywords: List[str]) -> Dict[str, Any]:
        """
        Gather intelligence from all available sources.
        
        Args:
            niche: Client's business niche
            keywords: Keywords related to the niche
        
        Returns:
            Dictionary with all intelligence data
        """
        print(f"\n🧠 Gathering intelligence for: {niche}")
        print("="*60)
        
        # Gather from all sources in parallel
        news_task = self.get_news_intelligence(niche)
        youtube_task = self.get_youtube_trends(keywords)
        
        news, youtube = await asyncio.gather(news_task, youtube_task)
        
        intelligence = {
            "niche": niche,
            "news": news,
            "youtube_trends": youtube,
            "timestamp": datetime.now().isoformat()
        }
        
        print("="*60)
        print(f"✅ Intelligence gathering complete!\n")
        
        return intelligence
    
    # =============================================================================
    # CONTENT IDEA GENERATION
    # =============================================================================
    
    async def generate_content_ideas(
        self,
        niche: Optional[str] = None,
        num_ideas: int = 5,
        platforms: Optional[List[str]] = None,
        goals: Optional[List[str]] = None,
        themes: Optional[List[str]] = None,
        exclude_topics: Optional[List[str]] = None,
        additional_context: str = ""
    ) -> List[ContentIdea]:
        """
        Generate content ideas based on client niche and parameters.
        
        Args:
            niche: Client's business niche/industry (uses client profile if not provided)
            num_ideas: Number of ideas to generate
            platforms: Specific platforms to focus on (uses niche platforms if not provided)
            goals: Specific goals (engagement, growth, conversions)
            themes: Specific themes/topics to explore (uses content pillars if not provided)
            exclude_topics: Topics to avoid
            additional_context: Extra context for idea generation
        
        Returns:
            List of ContentIdea objects ready for other agents
        """
        # Use client profile settings as defaults
        if not niche and self.client_profile:
            niche_value = self.client_profile.niche.value if hasattr(self.client_profile.niche, 'value') else self.client_profile.niche
            niche = niche_value.replace('_', ' ')
        elif not niche:
            niche = "general business"
        
        if not platforms and self.client_profile:
            platforms = self.client_profile.platforms
        
        if not themes and self.client_profile and self.client_profile.content_pillars:
            # content_pillars is a list of strings
            themes = self.client_profile.content_pillars if isinstance(self.client_profile.content_pillars, list) else [self.client_profile.content_pillars]
        
        print(f"\n🧠 Marketing Intelligence Agent: Generating {num_ideas} content ideas...")
        print(f"   Niche: {niche}")
        print(f"   Platforms: {platforms or 'all'}")
        
        # Get client context
        context = self._get_client_context(niche, additional_context)
        
        # Build platform constraints
        target_platforms = platforms or ["instagram", "facebook", "tiktok", "linkedin"]
        
        # Get deep research context from knowledge base
        deep_research_context = self._get_deep_research_context(target_platforms, themes)
        
        # Get proven strategy framework for this niche
        print(f"\n📚 Loading strategy framework for {niche}...")
        content_pillar_framework = self._get_strategy_framework('content_pillars', niche)
        hooks_framework = self._get_strategy_framework('hooks', niche)
        
        # Gather real-time intelligence
        print(f"\n📡 Gathering real-time intelligence...")
        keywords = themes if themes else [niche]
        intelligence = await self.gather_all_intelligence(niche, keywords)
        
        # Build intelligence context
        intelligence_context = ""
        
        if intelligence.get("news"):
            news_items = "\n".join([
                f"- {item['title']} ({item['source']})" 
                for item in intelligence["news"][:3]
            ])
            intelligence_context += f"\n**RECENT NEWS IN {niche.upper()}:**\n{news_items}\n"
        
        if intelligence.get("youtube_trends"):
            video_items = "\n".join([
                f"- {item['title']} ({item['channel']})" 
                for item in intelligence["youtube_trends"][:3]
            ])            
            intelligence_context += f"\n**TRENDING YOUTUBE CONTENT:**\n{video_items}\n"

        # Inject last week's performance data so Claude prefers proven formats
        perf_data = self._load_performance_data()
        if perf_data:
            intelligence_context += f"\n**LAST WEEK'S PERFORMANCE DATA (use this to prioritize content types and platforms that worked best):**\n{perf_data}\n"

        platform_formats = {p: self.PLATFORM_FORMATS.get(p, ["post"]) for p in target_platforms}
        
        # Build goals list
        target_goals = goals or ["views_engagement", "follower_growth", "conversions_sales"]
        
        prompt = f"""You are a senior marketing strategist specializing in social media content strategy.

Generate {num_ideas} unique content ideas for a business in the "{niche}" niche.

⚠️  CRITICAL — READ THE CLIENT CONTEXT BELOW CAREFULLY.
Every topic you generate MUST be written **from the perspective of this specific business**,
showcasing THEIR expertise, services, and value proposition.
Do NOT generate generic industry news articles or broad niche content.
Instead, generate thought-leadership, case-study-style, educational, and behind-the-scenes
content that would attract THIS business's target audience and position them as experts.
If the client context includes a business description, services, or target audience,
use those details to shape every single topic.

**CLIENT CONTEXT:**
{context}
{intelligence_context}

{content_pillar_framework}

{hooks_framework}

{deep_research_context}

**AVAILABLE PLATFORMS & FORMATS:**
{json.dumps(platform_formats, indent=2)}

**TARGET GOALS:**
{json.dumps(target_goals)}

**THEMES TO EXPLORE:**
{json.dumps(themes or ["industry trends", "tips & tricks", "behind the scenes", "customer stories", "educational content"])}

**TOPICS TO AVOID:**
{json.dumps(exclude_topics or [])}

**REQUIREMENTS:**
1. **FOLLOW THE PROVEN STRATEGY FRAMEWORK ABOVE** - Apply the structure, best practices, and optimize for the key metrics
2. Each idea must have a unique angle/perspective
3. Ideas should be diverse in format (mix of video, image, carousel, text)
4. Include specific hooks that stop the scroll (use proven hook formulas from framework)
5. Suggest 2-3 keywords/hashtags per idea
6. Prioritize based on potential impact and framework alignment
7. IMPORTANT: Apply the deep research insights (algorithm knowledge, viral patterns, optimal posting strategies)
8. Consider current trends in the niche (use the real-time intelligence)
9. Leverage trending topics from news and YouTube when relevant
10. Ensure content mix aligns with the proven framework ratios (e.g., 70% educational, 30% promotional)
11. **USE LAST WEEK'S PERFORMANCE DATA** - If provided above, bias format choices and platforms toward what drove the highest engagement. Produce more ideas similar to top-performing content and fewer of formats that underperformed.

**OUTPUT FORMAT:**
Return a JSON array of content ideas. Each idea must have:
{{
    "topic": "Main topic",
    "angle": "Unique perspective or hook",
    "format": "post|reel|story|carousel|video|article|thread",
    "goal": "views_engagement|follower_growth|conversions_sales",
    "recommended_platforms": ["instagram", "tiktok"],
    "hooks": ["Hook 1", "Hook 2"],
    "keywords": ["keyword1", "keyword2", "keyword3"],
    "priority": "high|medium|low",
    "reasoning": "Why this idea will perform well",
    "estimated_engagement": "low|medium|high",
    "media_type": "image|video|carousel|none",
    "call_to_action": "What action should viewers take"
}}

Return ONLY the JSON array, no other text."""

        try:
            response = self.claude_client.messages.create(
                model=self.model,
                max_tokens=4000,
                messages=[{"role": "user", "content": prompt}]
            )
            
            # Parse JSON response
            response_text = response.content[0].text.strip()
            
            # Clean up potential JSON issues
            if response_text.startswith("```json"):
                response_text = response_text[7:]
            if response_text.startswith("```"):
                response_text = response_text[3:]
            if response_text.endswith("```"):
                response_text = response_text[:-3]
            response_text = response_text.strip()

            # Try to extract JSON array via regex if direct parse fails
            try:
                ideas_data = json.loads(response_text)
            except json.JSONDecodeError:
                # Try extracting [...] from response
                arr_match = re.search(r'\[.*\]', response_text, re.DOTALL)
                if arr_match:
                    raw = arr_match.group(0)
                    # Repair truncated JSON: close open strings/objects
                    raw = _repair_truncated_json(raw)
                    ideas_data = json.loads(raw)
                else:
                    raise
            
            # Convert to ContentIdea objects
            ideas = []
            for data in ideas_data:
                idea = ContentIdea(
                    idea_id=self._generate_idea_id(),
                    topic=data.get("topic", ""),
                    angle=data.get("angle", ""),
                    format=data.get("format", "post"),
                    goal=data.get("goal", "views_engagement"),
                    recommended_platforms=data.get("recommended_platforms", ["instagram"]),
                    hooks=data.get("hooks", []),
                    keywords=data.get("keywords", []),
                    priority=data.get("priority", "medium"),
                    reasoning=data.get("reasoning", ""),
                    estimated_engagement=data.get("estimated_engagement", "medium"),
                    media_type=data.get("media_type", "image"),
                    call_to_action=data.get("call_to_action"),
                    best_posting_time=self.OPTIMAL_TIMES.get(
                        data.get("recommended_platforms", ["instagram"])[0], 
                        ["12:00 PM"]
                    )[0]
                )
                ideas.append(idea)
            
            print(f"✅ Generated {len(ideas)} content ideas")
            return ideas
            
        except json.JSONDecodeError as e:
            print(f"❌ Failed to parse AI response as JSON: {e}")
            print(f"   Response: {response_text[:500]}...")
            return []
        except Exception as e:
            print(f"❌ Error generating ideas: {e}")
            return []
    
    async def generate_weekly_strategy(
        self,
        niche: Optional[str] = None,
        posts_per_week: Optional[int] = None,
        platforms: Optional[List[str]] = None,
        themes: Optional[List[str]] = None,
        additional_context: str = ""
    ) -> ContentStrategy:
        """
        Generate a complete weekly content strategy.
        
        Args:
            niche: Client's business niche (uses client profile if not provided)
            posts_per_week: Target number of posts per week (uses posting_frequency if not provided)
            platforms: Platforms to post on (uses niche platforms if not provided)
            themes: Themes for the week (uses content pillars if not provided)
            additional_context: Extra context
        
        Returns:
            ContentStrategy with organized ideas for the week
        """
        # Use client profile settings as defaults
        if not niche and self.client_profile:
            niche_value = self.client_profile.niche.value if hasattr(self.client_profile.niche, 'value') else self.client_profile.niche
            niche = niche_value.replace('_', ' ')
        elif not niche:
            niche = "general business"
        
        if not posts_per_week and self.client_profile:
            posts_per_week = self.client_profile.posting_frequency
        elif not posts_per_week:
            posts_per_week = 7
        
        if not platforms and self.client_profile:
            platforms = self.client_profile.platforms
        
        if not themes and self.client_profile and self.client_profile.content_pillars:
            themes = self.client_profile.content_pillars if isinstance(self.client_profile.content_pillars, list) else [self.client_profile.content_pillars]
        
        print(f"\n📅 Generating weekly content strategy for {niche}...")
        print(f"   Posts per week: {posts_per_week}")
        if platforms:
            print(f"   Platforms: {', '.join(platforms)}")
        if themes:
            print(f"   Themes: {', '.join(themes[:3])}...")
        
        # Generate ideas
        ideas = await self.generate_content_ideas(
            niche=niche,
            num_ideas=posts_per_week,
            platforms=platforms,
            themes=themes,
            additional_context=additional_context
        )
        
        # Calculate content mix
        format_counts = {}
        for idea in ideas:
            fmt = idea.format
            format_counts[fmt] = format_counts.get(fmt, 0) + 1
        
        total = len(ideas) or 1
        content_mix = {fmt: int((count / total) * 100) for fmt, count in format_counts.items()}
        
        # Generate strategy
        today = datetime.now()
        strategy = ContentStrategy(
            strategy_id=self._generate_strategy_id(),
            client_id=self.client_id,
            period="weekly",
            start_date=today.strftime("%Y-%m-%d"),
            end_date=(today + timedelta(days=7)).strftime("%Y-%m-%d"),
            ideas=ideas,
            content_mix=content_mix,
            posting_frequency=posts_per_week,
            themes=themes or ["engagement", "education", "promotion"],
            notes=f"Weekly strategy for {niche}. Focus on consistency and engagement."
        )
        
        print(f"✅ Generated weekly strategy with {len(ideas)} content ideas")
        return strategy
    
    async def generate_campaign_ideas(
        self,
        niche: str,
        campaign_goal: str,
        duration_days: int = 7,
        platforms: Optional[List[str]] = None
    ) -> List[ContentIdea]:
        """
        Generate ideas for a specific marketing campaign.
        
        Args:
            niche: Client's business niche
            campaign_goal: Specific campaign goal (e.g., "product launch", "holiday sale")
            duration_days: Campaign duration
            platforms: Target platforms
        
        Returns:
            List of ContentIdea objects for the campaign
        """
        print(f"\n🎯 Generating campaign ideas for: {campaign_goal}")
        
        return await self.generate_content_ideas(
            niche=niche,
            num_ideas=duration_days * 2,  # 2 posts per day during campaign
            platforms=platforms,
            goals=["conversions_sales"],  # Campaigns focus on conversions
            themes=[campaign_goal, "urgency", "social proof", "value proposition"],
            additional_context=f"This is for a {duration_days}-day campaign focused on: {campaign_goal}"
        )
    
    def get_idea_for_platform(
        self, 
        ideas: List[ContentIdea], 
        platform: str
    ) -> Optional[ContentIdea]:
        """Get the best idea for a specific platform"""
        for idea in ideas:
            if platform in idea.recommended_platforms:
                return idea
        return ideas[0] if ideas else None
    
    def prioritize_ideas(self, ideas: List[ContentIdea]) -> List[ContentIdea]:
        """Sort ideas by priority (high first)"""
        priority_order = {"high": 0, "medium": 1, "low": 2}
        return sorted(ideas, key=lambda x: priority_order.get(x.priority, 1))


# =============================================================================
# CONVENIENCE FUNCTIONS
# =============================================================================

async def generate_ideas(
    client_id: str,
    niche: str,
    num_ideas: int = 5,
    platforms: Optional[List[str]] = None
) -> List[ContentIdea]:
    """Quick function to generate content ideas"""
    agent = MarketingIntelligenceAgent(client_id)
    return await agent.generate_content_ideas(niche, num_ideas, platforms)


async def generate_strategy(
    client_id: str,
    niche: str,
    posts_per_week: int = 7
) -> ContentStrategy:
    """Quick function to generate weekly strategy"""
    agent = MarketingIntelligenceAgent(client_id)
    return await agent.generate_weekly_strategy(niche, posts_per_week)


# =============================================================================
# TEST HARNESS
# =============================================================================

async def main():
    """Test the Marketing Intelligence Agent"""
    print("="*80)
    print("🧠 MARKETING INTELLIGENCE AGENT TEST")
    print("="*80)
    
    agent = MarketingIntelligenceAgent(client_id="demo_client")
    
    # Test 1: Generate content ideas
    print("\n📋 TEST 1: Generate Content Ideas")
    print("-"*40)
    
    ideas = await agent.generate_content_ideas(
        niche="AI automation for small businesses",
        num_ideas=5,
        platforms=["instagram", "linkedin", "tiktok"],
        themes=["productivity tips", "AI myths debunked", "success stories"]
    )
    
    for i, idea in enumerate(ideas, 1):
        print(f"\n💡 Idea {i}: {idea.topic}")
        print(f"   Angle: {idea.angle}")
        print(f"   Format: {idea.format} | Goal: {idea.goal}")
        print(f"   Platforms: {', '.join(idea.recommended_platforms)}")
        print(f"   Hooks: {idea.hooks[:2]}")
        print(f"   Priority: {idea.priority} | Engagement: {idea.estimated_engagement}")
    
    # Test 2: Generate weekly strategy
    print("\n\n📅 TEST 2: Generate Weekly Strategy")
    print("-"*40)
    
    strategy = await agent.generate_weekly_strategy(
        niche="AI automation for small businesses",
        posts_per_week=7,
        platforms=["instagram", "linkedin"]
    )
    
    print(f"\n📊 Strategy: {strategy.strategy_id}")
    print(f"   Period: {strategy.start_date} to {strategy.end_date}")
    print(f"   Posts: {strategy.posting_frequency}/week")
    print(f"   Content Mix: {strategy.content_mix}")
    print(f"   Themes: {strategy.themes}")
    print(f"   Total Ideas: {len(strategy.ideas)}")
    
    # Test 3: Convert idea to content request
    print("\n\n🔄 TEST 3: Convert Idea to Content Request")
    print("-"*40)
    
    if ideas:
        content_request = ideas[0].to_content_request()
        print(f"   Content Request: {json.dumps(content_request, indent=2)}")
    
    print("\n" + "="*80)
    print("✅ MARKETING INTELLIGENCE AGENT TEST COMPLETE")
    print("="*80)


if __name__ == "__main__":
    asyncio.run(main())
